options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/kubernetes-assignment-428919/k8s-assignment/container1:lt',
      '-f',
      'Dockerfile', 
      '.',
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetesassignment-417521/kubernetes-assignment/container-1:lt']
 
images:
- 'us-central1-docker.pkg.dev/kubernetes-assignment-428919/k8s-assignment/container1:lt'